### ISSUE TITLE
Unable to get status of user

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/LabLogin-Backend#2]
There is something wrong happening with the backend. Check it:

![capture](https://cloud.githubusercontent.com/assets/12587480/16402028/16922600-3c9e-11e6-9dd5-774cefaa64c3.PNG)

These are from one succession. When try and retrieve if the user exists, it always says that it does not exists. But once I register it again it says that it does exists.

**Comment by FelixVicis** [comment]
Are these done in quick succession? It could be that Datastore has not yet updated.

**Comment by pgonzbecer** [comment]
Not much. If there is "no user that exists" it opens up an input menu, then goes through the backend to register the user once the user is ready

**Comment by FelixVicis** [comment]
Okay, the storage solution we _were_ using had a latency issue where if you tried within a second of placing a value to check it. It was not yet updated. Attempting the alternate, less latent solution. Deployed. 

Try again.

**Comment by pgonzbecer** [comment]
Nope, still giving me the same problem

**Comment by FelixVicis** [comment]
Can you describe your actions in detail, I'll have to trace down the issue then.

**Comment by pgonzbecer** [comment]
Typed in my banner id, 00316362,
pressed enter and went through this link: http://ens-lablogin-backend.appspot.com/select state from record?Domain="+domain+"&User-Domain="+userDomain+"&UUID="+uuid,
Console logged, "No such user exists",
Popup pops up asking for first and last name,
Typed in my name, "Paul" in one, and "Gonzalez-Becerra" in the other,
Hit submit,
code goes through this link: http://ens-lablogin-backend.appspot.com/insert into user?User-Domain='+arg1+'&First='+arg2+'&Last='+arg3+'&UUID='+arg4,
Console logged, "User is already registered",
code then goes through this link: http://ens-lablogin-backend.appspot.com/toggle state from record?Domain='+arg1+'&User-Domain='+arg2+'&UUID='+arg3,
Console logged, "User is logged [ in / out ]"

**Comment by FelixVicis** [comment]
Do me a favor and try this with a new user. We may still be hitting the latency issue.

**Comment by pgonzbecer** [comment]
I tried it with banner id 99999999, 88998899, and 99889988. Gave me the same result

**Comment by FelixVicis** [comment]
Have you done uncommitted changes to the front end? I'm trying to also do this on my end.

**Comment by pgonzbecer** [comment]
I didn't change anything from when I found the bug

**Comment by FelixVicis** [comment]
:/ The submit button will not do anything when I try to use it on my end.

**Comment by pgonzbecer** [comment]
Oh right, the id number has to be 8 digits long or it wont let it go through

**Comment by FelixVicis** [comment]
You have Domain and User-Domain Backwards.

**Domain**: 0c228bdb-eea1-44be-7080-b1682faf26a5
**User-Domain**: 960fb362-35f2-4525-48dc-279795cc5bfb
**UUID**: 10110110

Users in this case is actually 0c..., and Domain is actually 960....

While testing it may benefit to fix the Domain and User-Domain with easy to read strings.

**Comment by FelixVicis** [comment]
Also, do you know that Jquery's post can take a parameters input?
`$.POST(url,{ParamName: "Value"},callback);`

would do the same as `url?ParamName=Value`

**Comment by pgonzbecer** [comment]
Oh... Um, where was my code wrong, or was the `seta_students` and `fnl_lab` variables mixed around?

Also my banner id, 00316362, now sort of works, only on logging in and never logging out. But any other codes I type in still experience the same problem, despite swapping the domain and user-domain

**Comment by pgonzbecer** [comment]
So it seems like I or Redden both mixed up things and there is a latency problem

**Comment by FelixVicis** [comment]
Short of tearing the whole thing apart and rebuilding, I have no idea where you mixed up your variables. At this point, I have to assume that the ajax calls are incorrectly formed rather than the back-end faulty. If you do want me to come over to front-end, have @johnRedden add me to it.

**Comment by pgonzbecer** [comment]
I got no clue why this one isn't working nicely and the predecessor did.

**Comment by FelixVicis** [comment]
I would check your functions that have collections of arg1, arg2 ...

It get's hard to know what anything does without clear parameter names

**Comment by johnRedden** [comment]
The arg names are my fault.  You are added to the login... but you can always see the code on github too:  https://github.com/johnRedden/LabLogin

**Comment by FelixVicis** [comment]
I know I can view it, that was how I figured out the backwards parameters.
Paul, if you want me to work on those JQ calls and clean it up a bit, let
me know.

**Comment by pgonzbecer** [comment]
If the revised version of the backend gives me more problems, then I will ask for a revision with the jQ calls.

**Comment by FelixVicis** [comment]
Okay, just let me know.
