### ISSUE TITLE
Getting an error from getting the record of logins

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/LabLogin-Backend#3]
So, not entirely sure if this is my fault or not. But I try and use this api link:

`"http://ens-lablogin-backend.appspot.com/select all from record?Domain="+domain`
With the domain being:

**Domain:** 960fb362-35f2-4525-48dc-279795cc5bfb

Comes up with this error:

> {"Status":"Failure","Reason":"API error 4 (datastore_v3: NEED_INDEX): no matching index found. recommended index is:\n- kind: 960fb362-35f2-4525-48dc-279795cc5bfb-Records\n  properties:\n  - name: In\n  - name: UUID\n","Code":500,"Results":null}

I got no clue what it's asking for nor do I know how to index it, if it is asking me for that

**Comment by FelixVicis** [comment]
it thinks your domain key is false. ill check on it.

**Comment by FelixVicis** [comment]
Okay, I was actually concerned that this would become an issue flying fast with these tables as I have. I have a solution, I'll just need to implement it.

This will result in your students and records becoming invalid, however it will clean up some other issues.

**Comment by pgonzbecer** [comment]
Alrighty

**Comment by FelixVicis** [comment]
Okay. Give it about 10 ish minutes for the new index to load up. After that try it.

Reminding note: you no longer have access to any of the students or records from before. Usage is identical but the backend is rather different.

**Comment by FelixVicis** [comment]
It's good to go now.
