### ISSUE TITLE
Lossy retrieval

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/LabLogin-Backend#4]
So another thing I noticed was that we are not retrieving all the information we should. At this point I am assuming because of [Issue # 3](https://github.com/johnRedden/LabLogin-Backend/issues/3), but from what I read on the wiki.

> Results are a json struct list of UUID, Time in, Time out

It is not returning a first and last, or full name with that object. Which would make registering with your name redundant.

**Comment by pgonzbecer** [comment]
Quote was taken [from here](https://github.com/johnRedden/LabLogin-Backend/wiki#get-record-of-logins)

**Comment by FelixVicis** [comment]
This is a storage implementation issue, not so much as a retrieval issue.

Registering was always less of a requirement on the back-end as it was a front end nicety. This can be cleaned up, it just makes the call a bit more involved.

**Comment by FelixVicis** [comment]
Solved. Toggle state now returns user info.
